title: Interactive Linear Algebra
description: Master the Mathematics Behind AI & Data Science
author: Zeeshan Modi
github_username: Zeesejo

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# GitHub Pages settings
repository: Zeesejo/LinearAlgebra
url: "https://zeesejo.github.io"
baseurl: "/LinearAlgebra"

# Exclude from processing
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - .github/

# Include in processing
include:
  - _redirects

# SEO settings
lang: en_US
twitter:
  username: # Add your Twitter username if you have one
  card: summary

social:
  name: Zeeshan Modi
  links:
    - https://github.com/Zeesejo

# Analytics (uncomment and add your tracking ID if you want analytics)
# google_analytics: UA-NNNNNNNN-N
